title: hello ðŸ‘‹ðŸ¾, i'm byron! 
author: Byron Yego 
email: byronyego@gmail.com
url: https://byron.wtf.dev 
baseurl: "/no-style-please" 
description: > 
  A (nearly) no-CSS, fast, minimalist Jekyll site for Byron Yego

permalink: /:slug.html

favicon: "logo.png" # 
# goat_counter: "byron.wtf" 

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "..go back" 
  date_format: "%Y-%m-%d" 
  show_description: true 
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
