title: hello ðŸ‘‹ðŸ¾, i'm byron! 
author: Byron Yego 
email: byronyego@gmail.com
url: https://byron.wtf.dev 
baseurl: "/no-style-please" 
description: > 
  Hi, my name is Byron Yego & I'm a Kenyan-based ðŸ‡°ðŸ‡ª software engineer who specializes in building (and occasionally designing) exceptional digital experiences.

permalink: /:slug.html

favicon: "logo.png" # 
# goat_counter: "byron.wtf" 

theme: no-style-please 

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "..go back" 
  date_format: "%Y-%m-%d" 
  show_description: true 
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
