title: hello ðŸ‘‹ðŸ¾, i'm byron! 
author: Byron Yego 
email: byronyego@gmail.com
url: https://byron.wtf/ 
baseurl: "" 
description: > 
  Hi, my name is Byron Yego & I'm a Kenyan-based ðŸ‡°ðŸ‡ª software engineer who specializes in building (and occasionally designing) exceptional digital experiences.

permalink: /:slug.html

favicon: "favicon-32x32.png" # 
# goat_counter: "byron.wtf" 

renote_theme: riggraz/no-style-please 

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "..go back" 
  date_format: "%Y-%m-%d" 
  show_description: true 
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
