title: The Guide! # name of the site
author: Ot√°vio Vacari Martins # name of site's author
email: otavio.vac@gmail.com # email of site's author
url: theblockchainguide.org # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: The blockchain guide

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
